package repo

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"
)

var (
	ErrContinuationNotFound = errors.New("continuation not found")
	ErrTitleAlreadyExists = errors.New("title already exists")
	ErrContractNumberAlreadyExists = errors.New("contract number already exists")
	ErrConstraintViolation = errors.New("persistence constraint violation")
	ErrInternal = errors.New("internal persistence error")
)

// CreateResearchInput contains normalized persistence values, not HTTP input.
// Service supplies Gregorian YYYY-MM-DD dates and the normalized contract key.
// Identity, initial status and initial process are generated by SQLite.
type CreateResearchInput struct {
	Title, ResearchKind, ProjectType string
	ResponsibleProjectUnit, ResponsibleBudgetUnit string
	StartDate, EndDate string
	ThaiAbstract, EnglishAbstract, Objectives, Keywords string
	IsSubsidized bool
	ContinuationOfID *int64
	BudgetAmount float64
	Members []ResearchMemberInput
	Contract ResearchContractInput
}

type ResearchMemberInput struct {
	FullName, Email, Affiliation, Role string
	ContributionPercent float64
}

type ResearchContractInput struct {
	FundingType, FundingSourceName, ContractNumber, ContractNumberKey string
	StoragePath, OriginalFilename, ContentType string
	SizeBytes int64
}

type ResearchRepository struct {
	database *sql.DB
}

func NewResearchRepository(database *sql.DB) *ResearchRepository {
	return &ResearchRepository{database: database}
}

// Create commits all three tables together and never returns an uncommitted ID.
// The first operation is an INSERT, avoiding a read-to-write lock upgrade when
// multiple connections concurrently create records with the same unique keys.
func (r *ResearchRepository) Create(ctx context.Context, input CreateResearchInput) (int64, error) {
	tx, err := r.database.BeginTx(ctx, nil)
	if err != nil {
		return 0, fmt.Errorf("%w: begin create: %v", ErrInternal, err)
	}
	defer tx.Rollback()
	result, err := tx.ExecContext(ctx, `INSERT INTO researches
		(title,is_subsidized,project_type,research_kind,continuation_of_id,
		 responsible_project_unit,responsible_budget_unit,start_date,end_date,
		 budget_amount,thai_abstract,english_abstract,objectives,keywords)
		VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		input.Title, input.IsSubsidized, input.ProjectType, input.ResearchKind, input.ContinuationOfID,
		input.ResponsibleProjectUnit, input.ResponsibleBudgetUnit, input.StartDate, input.EndDate,
		input.BudgetAmount, input.ThaiAbstract, input.EnglishAbstract, input.Objectives, input.Keywords)
	if err != nil {
		return 0, createError(err, true)
	}
	id, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("%w: generated ID: %v", ErrInternal, err)
	}
	for _, member := range input.Members {
		_, err := tx.ExecContext(ctx, `INSERT INTO research_members
			(research_id,full_name,email,affiliation,contribution_percent,role) VALUES (?,?,?,?,?,?)`,
			id, member.FullName, member.Email, member.Affiliation, member.ContributionPercent, member.Role)
		if err != nil {
			return 0, createError(err, false)
		}
	}
	c := input.Contract
	_, err = tx.ExecContext(ctx, `INSERT INTO research_contracts
		(research_id,funding_type,funding_source_name,contract_number,contract_number_key,
		 storage_path,original_filename,content_type,size_bytes) VALUES (?,?,?,?,?,?,?,?,?)`,
		id, c.FundingType, c.FundingSourceName, c.ContractNumber, c.ContractNumberKey,
		c.StoragePath, c.OriginalFilename, c.ContentType, c.SizeBytes)
	if err != nil {
		return 0, createError(err, false)
	}
	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("%w: commit create: %v", ErrInternal, err)
	}
	return id, nil
}

func createError(err error, insertingProject bool) error {
	kind := ErrInternal
	var sqliteErr *sqlite.Error
	if errors.As(err, &sqliteErr) {
		switch sqliteErr.Code() {
		case sqlite3.SQLITE_CONSTRAINT_TRIGGER:
			if strings.Contains(err.Error(), "research_title_already_exists") {
				kind = ErrTitleAlreadyExists
			} else if strings.Contains(err.Error(), "research_constraint_") {
				kind = ErrConstraintViolation
			}
		case sqlite3.SQLITE_CONSTRAINT_FOREIGNKEY:
			kind = ErrConstraintViolation
			if insertingProject {
				kind = ErrContinuationNotFound
			}
		case sqlite3.SQLITE_CONSTRAINT_UNIQUE:
			kind = ErrConstraintViolation
			if strings.Contains(err.Error(), "research_contracts.contract_number_key") {
				kind = ErrContractNumberAlreadyExists
			}
		case sqlite3.SQLITE_CONSTRAINT_CHECK, sqlite3.SQLITE_CONSTRAINT_NOTNULL, sqlite3.SQLITE_CONSTRAINT_PRIMARYKEY:
			kind = ErrConstraintViolation
		}
	}
	return fmt.Errorf("%w: %v", kind, err)
}
